name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: pytest
        run: |
            pytest tests  --cov=com --cov-report=html
      - name: ruff
        run: |
          pip install ruff
          ruff --output-format=github .
